//! Unicode lookup tables generated at build time.
//! This file is generated by the codegen system and should not be edited manually.

const props = @import("properties.zig");
const lut = @import("lut.zig");

/// Generated Unicode property lookup tables.
/// These tables are created from Unicode data files at build time.
pub const tables = lut.Tables(props.Properties){
    .stage1 = &[_]u16{0} ** 256,
    .stage2 = &[_]u16{0} ** 256,
    .stage3 = &[_]props.Properties{
        .{ .width = 1, .grapheme_boundary_class = .invalid },
        .{ .width = 2, .grapheme_boundary_class = .invalid },
    },
};
